name: Feel The Orient
favicon: null
layout_spectrum: 1
typography_spectrum: 0.37958
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#fbfbfb'
    - '#010302'
    - '#1070ba'
    - '#95bdb9'
    - '#49443a'
  brandStrength: 0.8290023400913924
  lightness: 0.7846392854116857
  saturation: 0.1875
  rhythmicContrast: 0.8997690707910806
purpose: []
